/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class as2_lqs_com_mylibrary_JNITest */

#ifndef _Included_as2_lqs_com_mylibrary_JNITest
#define _Included_as2_lqs_com_mylibrary_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     as2_lqs_com_mylibrary_JNITest
 * Method:    getStrFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_as2_lqs_com_mylibrary_JNITest_getStrFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
